---
title: "Lab 9"
author: "Jonathan Coombs"
format:
  html:
    code-fold: true
    toc: true
    toc_float: true
    embed-resources: true
editor: visual
execute:
  warning: false
  message: false
---

```{r, eval=FALSE}
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install(version = "3.21")

if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("ggtree")

if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("Biostrings")
```

```{r}
# You may need to install the treeio, rphylopic and ggimage packages
library(tidyverse)
library(ggtree)
library(treeio)
library(rphylopic)
# library(ggimage)
```

## Examples and Exercises

### Examples

```{r}
tree <- read.tree("/work/pi_bio678_umass_edu/data/lab13/tree_newick.nwk")
tree
# build a ggplot with a geom_tree
ggplot(tree) + geom_tree() + theme_tree()
# This is convenient shorthand
ggtree(tree)
# add a scale
ggtree(tree) + geom_treescale()
# or add the entire scale to the x axis with theme_tree2()
ggtree(tree) + theme_tree2()
ggtree(tree, branch.length="none")
ggtree(tree, branch.length="none", color="blue", size=2, linetype=3)
```

### Exercise 1

```{r}
ggtree(tree, layout="slanted")
ggtree(tree, layout="circular")
ggtree(tree, layout="circular", branch.length = "none", color = "red", size = 5)
```

### Examples

```{r}
# create the basic plot
p <- ggtree(tree)
# add node points
p + geom_nodepoint()
# add tip points
p + geom_tippoint()
# Label the tips
p + geom_tiplab()
```

### Exercise 2

```{r}
p <- ggtree(tree) + geom_tippoint(color="purple", shape="diamond") + geom_tiplab() + geom_nodepoint(color="yellow", alpha=0.5) + ggtitle("Phylogenetic Tree")
p
```

### Examples

```{r}
ggtree(tree) + geom_text(aes(label=node), hjust=-.3)
ggtree(tree) + geom_tiplab()
MRCA(tree, c("C", "E"))
MRCA(tree, c("G", "H"))
# MRCA(tree, tip=c("C", "E"))
# MRCA(tree, tip=c("G", "H"))
ggtree(tree) + 
  geom_cladelabel(node=17, label="Some random clade", color="red")
ggtree(tree) + 
  geom_tiplab() + 
  geom_cladelabel(node=17, label="Some random clade", 
                  color="red2", offset=.8)
ggtree(tree) + 
  geom_tiplab() + 
  geom_cladelabel(node=17, label="Some random clade", 
                  color="red2", offset=.8) + 
  geom_cladelabel(node=21, label="A different clade", 
                  color="blue", offset=.8)
ggtree(tree) + 
  geom_tiplab() + 
  geom_cladelabel(node=17, label="Some random clade", 
                  color="red2", offset=.8, align=TRUE) + 
  geom_cladelabel(node=21, label="A different clade", 
                  color="blue", offset=.8, align=TRUE) + 
  theme_tree2() + 
  xlim(0, 70) + 
  theme_tree()
ggtree(tree) + 
  geom_tiplab() + 
  geom_hilight(node=17, fill="gold") + 
  geom_hilight(node=21, fill="purple")
ggtree(tree) + 
  geom_tiplab() + 
  geom_taxalink("E", "H", color="blue3") +
  geom_taxalink("C", "G", color="orange2", curvature=-.9)
```

### Exercise 3

```{r}
p <- ggtree(tree) + geom_tiplab()
p <- p + geom_hilight(node=MRCA(tree, c("B", "C")), fill="blue") + geom_hilight(node=MRCA(tree, c("L", "J")), fill="red")
p <- p + geom_cladelabel(node=MRCA(tree, c("B", "E")), label = "Superclade 17", offset = 0.8) + geom_taxalink("C", "E", linetype=2) + geom_taxalink("G", "J", linetype=2) + theme_tree2() + ggtitle("Exercise 3 Phylotree")
p
```

### Examples

```{r}
# Read the data
tree <- read.beast("/work/pi_bio678_umass_edu/data/lab13/flu_tree_beast.tree")
# supply a most recent sampling date so you get the dates
# and add a scale bar
ggtree(tree, mrsd="2013-01-01") + 
  theme_tree2() 
# Finally, add tip labels and adjust axis
ggtree(tree, mrsd="2013-01-01") + 
  theme_tree2() + 
  geom_tiplab(align=TRUE, linesize=.5) + 
  xlim(1990, 2020)
```

```{r, eval=FALSE}
msaplot(p=ggtree(tree), fasta="/work/pi_bio678_umass_edu/data/lab13/flu_aasequence.fasta", window=c(150, 175))
set.seed(42)
trees <- lapply(rep(c(10, 25, 50, 100), 3), rtree)
class(trees) <- "multiPhylo"
ggtree(trees) + facet_wrap(~.id, scale="free", ncol=4) + ggtitle("Many trees. Such phylogenetics. Wow.")
# Generate a random tree with 30 tips
tree <- rtree(30)
# Make the original plot
p <- ggtree(tree)
# generate some random values for each tip label in the data
d1 <- data.frame(id=tree$tip.label, val=rnorm(30, sd=3))
# Make a second plot with the original, naming the new plot "dot", 
# using the data you just created, with a point geom.
p2 <- facet_plot(p, panel="dot", data=d1, geom=geom_point, aes(x=val), color='red3')
# Make some more data with another random value.
d2 <- data.frame(id=tree$tip.label, value = abs(rnorm(30, mean=100, sd=50)))
# Now add to that second plot, this time using the new d2 data above, 
# This time showing a bar segment, size 3, colored blue.
p3 <- facet_plot(p2, panel='bar', data=d2, geom=geom_segment, 
           aes(x=0, xend=value, y=y, yend=y), size=3, color='blue4') 
# Show all three plots with a scale
p3 + theme_tree2()
# get phylopic 

newick <- "((Pongo_abelii,(Gorilla_gorilla_gorilla,(Pan_paniscus,Pan_troglodytes)Pan,Homo_sapiens)Homininae)Hominidae,Nomascus_leucogenys)Hominoidea;"

tree <- read.tree(text=newick)

d <- ggimage::phylopic_uid(tree$tip.label)
d$body_mass = c(52, 114, 47, 45, 58, 6)

p <- ggtree(tree) %<+% d + 
  geom_tiplab(aes(image=uid, colour=body_mass), geom="phylopic", offset=2.5) +
  geom_tiplab(aes(label=label), offset = .2) + xlim(NA, 7) +
  scale_color_viridis_c()
p
# Add to your 
ggtree(tree) +
  xlim(0,2) # This worked from my rectangular trees
  xlim(0.36) # This worked for my circular trees
ggtree(tree) +  
  geom_nodelab()
ggtree(tree) +
  geom_tiplab(hjust=-.1, size = 3)
ggtree(tree) +
  geom_hilight(node=34, fill="gold", extend = 0.5)
```